package com.quranicwords.app.core.data.local.dao

import androidx.room.Dao
import androidx.room.Insert
import androidx.room.Query
import com.quranicwords.app.core.data.local.entity.ExerciseAttemptEntity
import kotlinx.coroutines.flow.Flow

@Dao
interface ExerciseAttemptDao {
    @Insert
    suspend fun insert(attempt: ExerciseAttemptEntity)

    @Insert
    suspend fun insertAll(attempts: List<ExerciseAttemptEntity>)

    @Query("SELECT * FROM exercise_attempts WHERE userId = :userId ORDER BY attemptedAtEpochMillis DESC LIMIT :limit")
    fun observeRecentForUser(userId: String, limit: Int): Flow<List<ExerciseAttemptEntity>>

    /** Full history for backup export - no limit, unlike [observeRecentForUser]. */
    @Query("SELECT * FROM exercise_attempts WHERE userId = :userId")
    suspend fun getAllForUser(userId: String): List<ExerciseAttemptEntity>

    /** Clears any existing rows for this user before a backup restore, so re-importing the same
     * file repeatedly doesn't pile up duplicate attempt rows (autogenerated ids give restored
     * rows fresh ids either way). */
    @Query("DELETE FROM exercise_attempts WHERE userId = :userId")
    suspend fun deleteForUser(userId: String)

    /**
     * Distinct `itemId`s whose most recent attempt was incorrect - a simple "last attempt wrong"
     * signal (not a full spaced-repetition scheduler). The correlated subquery picks each item's
     * single latest row by timestamp, then this filters to the ones where that latest row was
     * wrong. An item naturally drops out of this set the next time it's answered correctly.
     */
    @Query(
        """
        SELECT a.itemId FROM exercise_attempts a
        WHERE a.userId = :userId
        AND a.wasCorrect = 0
        AND a.attemptedAtEpochMillis = (
            SELECT MAX(b.attemptedAtEpochMillis) FROM exercise_attempts b
            WHERE b.userId = a.userId AND b.itemId = a.itemId
        )
        GROUP BY a.itemId
        """
    )
    suspend fun getMissedItemIds(userId: String): List<String>
}
