package com.quranicwords.app.core.data.local.dao

import androidx.room.Dao
import androidx.room.Insert
import androidx.room.Query
import com.quranicwords.app.core.data.local.entity.ExerciseAttemptEntity
import kotlinx.coroutines.flow.Flow

@Dao
interface ExerciseAttemptDao {
    @Insert
    suspend fun insert(attempt: ExerciseAttemptEntity)

    @Insert
    suspend fun insertAll(attempts: List<ExerciseAttemptEntity>)

    @Query("SELECT * FROM exercise_attempts WHERE userId = :userId ORDER BY attemptedAtEpochMillis DESC, id DESC LIMIT :limit")
    fun observeRecentForUser(userId: String, limit: Int): Flow<List<ExerciseAttemptEntity>>

    /** Full history for backup export - no limit, unlike [observeRecentForUser]. */
    @Query("SELECT * FROM exercise_attempts WHERE userId = :userId")
    suspend fun getAllForUser(userId: String): List<ExerciseAttemptEntity>

    /** Clears any existing rows for this user before a backup restore, so re-importing the same
     * file repeatedly doesn't pile up duplicate attempt rows (autogenerated ids give restored
     * rows fresh ids either way). */
    @Query("DELETE FROM exercise_attempts WHERE userId = :userId")
    suspend fun deleteForUser(userId: String)

    /**
     * Distinct `itemId`s whose most recent attempt was incorrect - a simple "last attempt wrong"
     * signal (not a full spaced-repetition scheduler). The correlated subquery picks each item's
     * single latest row by timestamp and id, then this filters to the ones where that latest row was
     * wrong. An item naturally drops out of this set the next time it's answered correctly.
     */
    @Query(
        """
        SELECT a.itemId FROM exercise_attempts a
        WHERE a.userId = :userId
        AND a.wasCorrect = 0
        AND a.id = (
            SELECT b.id FROM exercise_attempts b
            WHERE b.userId = a.userId AND b.itemId = a.itemId
            ORDER BY b.attemptedAtEpochMillis DESC, b.id DESC
            LIMIT 1
        )
        GROUP BY a.itemId
        """
    )
    suspend fun getMissedItemIds(userId: String): List<String>

    @Query(
        """
        SELECT a.itemId FROM exercise_attempts a
        WHERE a.userId = :userId
        AND a.wasCorrect = 0
        AND a.id = (
            SELECT b.id FROM exercise_attempts b
            WHERE b.userId = a.userId AND b.itemId = a.itemId
            ORDER BY b.attemptedAtEpochMillis DESC, b.id DESC
            LIMIT 1
        )
        GROUP BY a.itemId
        """
    )
    fun observeMissedItemIds(userId: String): Flow<List<String>>

    /** Inverse of [getMissedItemIds]: distinct `itemId`s whose most recent attempt was correct -
     * the derived definition of "words learned" used by the Progress tab (see
     * `com.quranicwords.app.feature.progress.ProgressViewModel`). Not a permanent "mastered"
     * flag - an item drops out of this set the next time it's answered wrong, same as
     * [getMissedItemIds]'s own "last attempt" semantics. */
    @Query(
        """
        SELECT a.itemId FROM exercise_attempts a
        WHERE a.userId = :userId
        AND a.wasCorrect = 1
        AND a.id = (
            SELECT b.id FROM exercise_attempts b
            WHERE b.userId = a.userId AND b.itemId = a.itemId
            ORDER BY b.attemptedAtEpochMillis DESC, b.id DESC
            LIMIT 1
        )
        GROUP BY a.itemId
        """
    )
    suspend fun getMasteredItemIds(userId: String): List<String>

    /** Every distinct `itemId` this user has ever attempted, regardless of correctness - the word
     * pool for Open Practice (falls back to the full corpus only when this is empty - see
     * `ProgressRepositoryImpl.getOpenPracticeExercises`) and, unlike that fallback, the *only*
     * source for a streak-recovery quiz, which must never quiz on a word the learner has never
     * actually studied. */
    @Query("SELECT DISTINCT itemId FROM exercise_attempts WHERE userId = :userId")
    suspend fun getAllPracticedItemIds(userId: String): List<String>
}
