package com.quranicwords.app.core.data.assets

import com.quranicwords.app.core.domain.model.ExerciseContent
import com.quranicwords.app.core.util.AppJson
import kotlinx.serialization.decodeFromString
import org.junit.Assert.assertEquals
import org.junit.Assert.assertNull
import org.junit.Assert.assertTrue
import org.junit.Test
import java.io.File

/**
 * Decodes every bundled content JSON asset through the real kotlinx.serialization types
 * ContentSeeder uses, catching shape mismatches (missing/misnamed fields) that a plain JSON
 * structural check can't - especially important for the vocabulary content, generated by
 * `tools/ingestion/11_build_curriculum.py` rather than hand-authored. Counts here are the actual
 * output of that script for the current 8-chapter/10-section/~10-word-lesson partition (see the
 * script's own assertions for the partition math) - re-run the script and update these counts
 * together if the partition ever changes.
 */
class GeneratedContentParsesTest {

    private val assetsDir = File("src/main/assets/content")

    private fun readAsset(name: String): String = File(assetsDir, name).readText()

    @Test
    fun `chapters json decodes, word counts sum to the full corpus, percents sum to 100`() {
        val file = AppJson.decodeFromString<ChaptersFile>(readAsset("chapters.json"))
        assertEquals(8, file.chapters.size)
        assertEquals(3680, file.chapters.sumOf { it.wordCount })
        assertEquals(100.0, file.chapters.sumOf { it.quranOccurrencePercent }, 0.01)
    }

    @Test
    fun `sections json decodes, ten per chapter, word counts sum to their chapter`() {
        val file = AppJson.decodeFromString<SectionsFile>(readAsset("sections.json"))
        assertEquals(80, file.sections.size)
        val byChapter = file.sections.groupBy { it.chapterId }
        assertEquals(8, byChapter.size)
        byChapter.values.forEach { sections ->
            assertEquals(10, sections.size)
            assertEquals(460, sections.sumOf { it.wordCount })
            sections.forEach { assertEquals(46, it.wordCount) }
        }
    }

    @Test
    fun `vocabulary lessons decode with correct counts per kind`() {
        val lessons = AppJson.decodeFromString<LessonsFile>(readAsset("lessons_vocabulary.json")).lessons
        assertEquals(887, lessons.size)

        val byKind = lessons.groupingBy { it.kind }.eachCount()
        assertEquals(400, byKind[com.quranicwords.app.core.data.local.entity.LessonKind.REGULAR])
        assertEquals(320, byKind[com.quranicwords.app.core.data.local.entity.LessonKind.LESSON_FLASHBACK])
        assertEquals(80, byKind[com.quranicwords.app.core.data.local.entity.LessonKind.SECTION_EXAM])
        assertEquals(72, byKind[com.quranicwords.app.core.data.local.entity.LessonKind.SECTION_FLASHBACK])
        assertEquals(8, byKind[com.quranicwords.app.core.data.local.entity.LessonKind.CHAPTER_EXAM])
        assertEquals(7, byKind[com.quranicwords.app.core.data.local.entity.LessonKind.CHAPTER_FLASHBACK])

        // Chapter-scoped kinds have no section; every other kind does.
        lessons.forEach { lesson ->
            val isChapterScoped = lesson.kind == com.quranicwords.app.core.data.local.entity.LessonKind.CHAPTER_EXAM ||
                lesson.kind == com.quranicwords.app.core.data.local.entity.LessonKind.CHAPTER_FLASHBACK
            if (isChapterScoped) assertNull(lesson.sectionId) else assertTrue(lesson.sectionId != null)
        }
    }

    @Test
    fun `vocabulary exercises decode and every teach step is a WordIntro`() {
        val exercises = AppJson.decodeFromString<ExercisesFile>(readAsset("exercises_vocabulary.json"))
        assertEquals(17540, exercises.exercises.size)

        val entities = exercises.exercises.map { it.toEntity() }
        assertEquals(17540, entities.size)

        val teachCount = exercises.exercises.count { it.content is ExerciseContent.WordIntro }
        assertEquals(3680, teachCount)

        val quizCount = exercises.exercises.count { it.content is ExerciseContent.MultipleChoice }
        assertEquals(13060, quizCount)

        val matchCount = exercises.exercises.count { it.content is ExerciseContent.Matching }
        assertEquals(800, matchCount)
    }

    @Test
    fun `word frequency file decodes with correct count and unique ranks`() {
        val file = AppJson.decodeFromString<WordFrequencyFile>(readAsset("word_frequency.json"))
        assertEquals(3680, file.words.size)
        val ranks = file.words.map { it.frequencyRank }.toSet()
        assertEquals(3680, ranks.size)
    }
}
