package com.quranicwords.app.core.data.assets

import com.quranicwords.app.core.domain.model.ExerciseContent
import com.quranicwords.app.core.util.AppJson
import kotlinx.serialization.decodeFromString
import org.junit.Assert.assertEquals
import org.junit.Assert.assertNull
import org.junit.Assert.assertTrue
import org.junit.Test
import java.io.File

/**
 * Decodes every bundled content JSON asset through the real kotlinx.serialization types
 * ContentSeeder uses, catching shape mismatches (missing/misnamed fields) that a plain JSON
 * structural check can't - especially important for the vocabulary content, generated by
 * `tools/ingestion/11_build_curriculum.py` rather than hand-authored. Counts here are the actual
 * output of that script for the current 8-chapter/10-section/~10-word-lesson partition (see the
 * script's own assertions for the partition math) - re-run the script and update these counts
 * together if the partition ever changes.
 */
class GeneratedContentParsesTest {

    private val assetsDir = File("src/main/assets/content")

    private fun readAsset(name: String): String = File(assetsDir, name).readText()

    @Test
    fun `chapters json decodes, word counts sum to the full corpus, percents sum to 100`() {
        val file = AppJson.decodeFromString<ChaptersFile>(readAsset("chapters.json"))
        assertEquals(8, file.chapters.size)
        assertEquals(3680, file.chapters.sumOf { it.wordCount })
        assertEquals(100.0, file.chapters.sumOf { it.quranOccurrencePercent }, 0.01)
    }

    @Test
    fun `sections json decodes, ten per chapter, word counts sum to their chapter`() {
        val file = AppJson.decodeFromString<SectionsFile>(readAsset("sections.json"))
        assertEquals(80, file.sections.size)
        val byChapter = file.sections.groupBy { it.chapterId }
        assertEquals(8, byChapter.size)
        byChapter.values.forEach { sections ->
            assertEquals(10, sections.size)
            assertEquals(460, sections.sumOf { it.wordCount })
            sections.forEach { assertEquals(46, it.wordCount) }
        }
    }

    @Test
    fun `vocabulary lessons decode with correct counts per kind`() {
        val lessons = AppJson.decodeFromString<LessonsFile>(readAsset("lessons_vocabulary.json")).lessons
        assertEquals(887, lessons.size)

        val byKind = lessons.groupingBy { it.kind }.eachCount()
        assertEquals(400, byKind[com.quranicwords.app.core.data.local.entity.LessonKind.REGULAR])
        assertEquals(320, byKind[com.quranicwords.app.core.data.local.entity.LessonKind.LESSON_FLASHBACK])
        assertEquals(80, byKind[com.quranicwords.app.core.data.local.entity.LessonKind.SECTION_EXAM])
        assertEquals(72, byKind[com.quranicwords.app.core.data.local.entity.LessonKind.SECTION_FLASHBACK])
        assertEquals(8, byKind[com.quranicwords.app.core.data.local.entity.LessonKind.CHAPTER_EXAM])
        assertEquals(7, byKind[com.quranicwords.app.core.data.local.entity.LessonKind.CHAPTER_FLASHBACK])

        // Chapter-scoped kinds have no section; every other kind does.
        lessons.forEach { lesson ->
            val isChapterScoped = lesson.kind == com.quranicwords.app.core.data.local.entity.LessonKind.CHAPTER_EXAM ||
                lesson.kind == com.quranicwords.app.core.data.local.entity.LessonKind.CHAPTER_FLASHBACK
            if (isChapterScoped) assertNull(lesson.sectionId) else assertTrue(lesson.sectionId != null)
        }
    }

    @Test
    fun `vocabulary exercises decode and every teach step is a WordIntro`() {
        val exercises = AppJson.decodeFromString<ExercisesFile>(readAsset("exercises_vocabulary.json"))
        assertEquals(19122, exercises.exercises.size)

        val entities = exercises.exercises.map { it.toEntity() }
        assertEquals(19122, entities.size)

        val teachCount = exercises.exercises.count { it.content is ExerciseContent.WordIntro }
        assertEquals(3680, teachCount)

        val quizCount = exercises.exercises.count { it.content is ExerciseContent.MultipleChoice }
        assertEquals(13060, quizCount)

        val matchCount = exercises.exercises.count { it.content is ExerciseContent.Matching }
        assertEquals(800, matchCount)

        // Reverse-direction "tap the word in the verse" quiz - only for words with a confirmed
        // arabicWordStart/End span (see docs/CONTENT_SOURCES.md item 9).
        val tapWordCount = exercises.exercises.count { it.content is ExerciseContent.TapWordInVerse }
        assertEquals(1582, tapWordCount)

        // Every TapWordInVerse's correct span must actually be one of its own tappable spans -
        // otherwise the UI could never register a correct tap.
        exercises.exercises.map { it.content }.filterIsInstance<ExerciseContent.TapWordInVerse>().forEach {
            assertTrue(
                it.tappableSpans.any { span -> span.start == it.correctWordStart && span.end == it.correctWordEnd }
            )
        }
    }

    @Test
    fun `word frequency file decodes with correct count and unique ranks`() {
        val file = AppJson.decodeFromString<WordFrequencyFile>(readAsset("word_frequency.json"))
        assertEquals(3680, file.words.size)
        val ranks = file.words.map { it.frequencyRank }.toSet()
        assertEquals(3680, ranks.size)
    }

    // Phase 3/4/5 map-based localization (QW-47/48): every *En/*Bn field pair was replaced with a
    // LocalizedText (Map<String, String>) map. These assertions specifically exercise that shape,
    // not just "the file happens to decode" - a regression back to a flat/partial map (e.g. a
    // future script accidentally overwriting `meaning` instead of merging into it) would fail here
    // even though the file would still structurally decode.
    private val allLanguageTags = setOf("en", "bn", "sq", "zh", "fa", "fr", "de", "hi", "in", "ru", "tr", "ur")

    @Test
    fun `every word_intro prompt covers all 12 languages`() {
        val exercises = AppJson.decodeFromString<ExercisesFile>(readAsset("exercises_vocabulary.json"))
        val wordIntros = exercises.exercises.map { it.content }.filterIsInstance<ExerciseContent.WordIntro>()
        assertEquals(3680, wordIntros.size)
        wordIntros.forEach { assertEquals(allLanguageTags, it.prompt.keys) }
    }

    @Test
    fun `word_intro meaning always has en+bn, and a real majority of spanned words have all 12 languages`() {
        val exercises = AppJson.decodeFromString<ExercisesFile>(readAsset("exercises_vocabulary.json"))
        val wordIntros = exercises.exercises.map { it.content }.filterIsInstance<ExerciseContent.WordIntro>()
        wordIntros.forEach {
            assertTrue("meaning missing en/bn for ${it.wordId}", it.meaning.keys.containsAll(setOf("en", "bn")))
        }

        // Only WordIntro entries with a confirmed verse span (arabicWordStart/End) can be matched
        // against the 12-language reference data by 13_translate_content_12lang.py - see
        // docs/CONTENT_SOURCES.md for the real, measured 87-98%-per-language match rate. This
        // count jumped from 1,582 to 3,668 after 15_reverify_example_verses.py replaced most
        // root-derived example verses with confirmed literal occurrences (QW-18).
        val spanned = wordIntros.filter { it.arabicWordStart != null && it.arabicWordEnd != null }
        assertTrue("expected at least 3668 spanned words, got ${spanned.size}", spanned.size >= 3668)
        val fullyTranslated = spanned.count { it.meaning.keys == allLanguageTags }
        assertTrue(
            "expected most spanned words to have all 12 languages, got $fullyTranslated/${spanned.size}",
            fullyTranslated > spanned.size * 3 / 4
        )
    }

    @Test
    fun `word_frequency meaning stays in sync with the matching word_intro meaning`() {
        val exercises = AppJson.decodeFromString<ExercisesFile>(readAsset("exercises_vocabulary.json"))
        val wordFreq = AppJson.decodeFromString<WordFrequencyFile>(readAsset("word_frequency.json"))
        val meaningByWordId = exercises.exercises.map { it.content }
            .filterIsInstance<ExerciseContent.WordIntro>()
            .associate { it.wordId to it.meaning }

        wordFreq.words.forEach { word ->
            val expected = meaningByWordId[word.id] ?: return@forEach
            assertEquals("meaning diverged for ${word.id}", expected, word.meaning)
        }
    }
}
