import org.jetbrains.kotlin.gradle.dsl.JvmTarget
import java.util.Properties
import java.io.File

plugins {
    alias(libs.plugins.android.application)
    alias(libs.plugins.kotlin.compose)
    alias(libs.plugins.kotlin.serialization)
    alias(libs.plugins.ksp)
    alias(libs.plugins.hilt)
}

// Release signing reads from a git-ignored keystore.properties (see .gitignore) rather than a
// committed keystore - deliberately NOT generated by tooling, since a lost/mishandled release
// key permanently breaks the ability to publish updates under the same app identity on Play
// Store. Generate your own (`keytool -genkeypair ...`) and create keystore.properties at the repo
// root with storeFile/storePassword/keyAlias/keyPassword before running :app:assembleRelease or
// :app:bundleRelease for real distribution. Falls back to no release signing config (the build
// still works for local verification via assembleRelease, just produces an unsigned/debug-signed
// artifact) when the properties file isn't present, so this doesn't break CI/local builds that
// never intend to publish.
val keystorePropertiesFile = rootProject.file("keystore.properties")
val keystoreProperties = Properties().apply {
    if (keystorePropertiesFile.exists()) {
        keystorePropertiesFile.inputStream().use { load(it) }
    }
}
val hasReleaseSigningConfig = keystorePropertiesFile.exists()

android {
    namespace = "com.quranicwords.app"
    compileSdk = 36
    ndkVersion = "28.2.13676358"

    defaultConfig {
        applicationId = "com.deanybytes.quranicwords"
        minSdk = 24
        targetSdk = 36
        versionCode = 27
        versionName = "1.0.0"

        testInstrumentationRunner = "androidx.test.runner.AndroidJUnitRunner"
    }

    signingConfigs {
        if (hasReleaseSigningConfig) {
            create("release") {
                storeFile = rootProject.file(keystoreProperties.getProperty("storeFile"))
                storePassword = keystoreProperties.getProperty("storePassword")
                keyAlias = keystoreProperties.getProperty("keyAlias")
                keyPassword = keystoreProperties.getProperty("keyPassword")
                enableV1Signing = true
                enableV2Signing = true
            }
        }
    }

    buildTypes {
        release {
            optimization {
                enable = true
            }
            proguardFiles(
                getDefaultProguardFile("proguard-android-optimize.txt"),
                "proguard-rules.pro"
            )
            ndk {
                debugSymbolLevel = "FULL"
            }
            if (hasReleaseSigningConfig) {
                signingConfig = signingConfigs.getByName("release")
            } else {
                signingConfig = signingConfigs.getByName("debug")
            }
        }
    }
    compileOptions {
        sourceCompatibility = JavaVersion.VERSION_11
        targetCompatibility = JavaVersion.VERSION_11
        // StreakCalculator/HomeViewModel/ProgressRepositoryImpl/ClockModule all use java.time
        // (Clock, LocalDate, ChronoUnit), which needs API 26+ without this - minSdk here is 24,
        // so without desugaring the app would crash on real API 24/25 devices the first time
        // streak logic runs (essentially immediately, on Home). Caught by :app:lint's NewApi
        // check while wiring lint into CI (QW-26) - a real correctness gap, not a style nag.
        isCoreLibraryDesugaringEnabled = true
    }
    buildFeatures {
        compose = true
        buildConfig = true
    }
    testOptions {
        unitTests {
            isIncludeAndroidResources = true
            isReturnDefaultValues = true
            all { test ->
                test.jvmArgs(
                    "-XX:-PrintWarnings",
                    "--enable-native-access=ALL-UNNAMED",
                    "--add-opens=java.base/java.lang=ALL-UNNAMED",
                    "--add-opens=java.base/java.util=ALL-UNNAMED",
                    "--add-opens=jdk.unsupported/sun.misc=ALL-UNNAMED",
                    "--add-exports=jdk.unsupported/sun.misc=ALL-UNNAMED",
                    "-Dprotobuf.disable_unsafe=true"
                )
            }
        }
    }
    bundle {
        language {
            enableSplit = false
        }
    }
    lint {
        warningsAsErrors = true
        abortOnError = true
        disable += listOf(
            "MissingTranslation",
            "PluralsCandidate",
            "Typos",
            "UnusedAttribute",
            "UnusedResources",
            "UnusedTranslation",
            "IconDuplicates",
            "AndroidGradlePluginVersion",
            "GradleDependency",
            "NewerVersionAvailable",
            "ObsoleteSdkInt",
            "OldTargetApi"
        )
    }

}

kotlin {
    compilerOptions {
        jvmTarget.set(JvmTarget.JVM_11)
        allWarningsAsErrors.set(true)
        freeCompilerArgs.add("-Xannotation-default-target=param-property")
    }
}

dependencies {
    implementation(libs.androidx.appcompat)
    implementation(libs.androidx.core.ktx)
    implementation(libs.material)

    val composeBom = platform(libs.androidx.compose.bom)
    implementation(composeBom)
    androidTestImplementation(composeBom)
    implementation(libs.androidx.compose.ui)
    implementation(libs.androidx.compose.ui.graphics)
    implementation(libs.androidx.compose.ui.tooling.preview)
    implementation(libs.androidx.compose.material3)
    implementation(libs.androidx.compose.material.icons.extended)
    implementation(libs.androidx.activity.compose)
    implementation(libs.androidx.lifecycle.viewmodel.compose)
    implementation(libs.androidx.lifecycle.runtime.compose)
    implementation(libs.androidx.navigation.compose)
    implementation(libs.androidx.core.splashscreen)
    debugImplementation(libs.androidx.compose.ui.tooling)

    implementation(libs.hilt.android)
    ksp(libs.hilt.android.compiler)
    implementation(libs.androidx.hilt.navigation.compose)

    implementation(libs.androidx.work.runtime.ktx)
    implementation(libs.androidx.hilt.work)
    ksp(libs.androidx.hilt.compiler)

    implementation(libs.androidx.room.runtime)
    implementation(libs.androidx.room.ktx)
    ksp(libs.androidx.room.compiler)

    implementation(libs.kotlinx.coroutines.android)
    implementation(libs.kotlinx.serialization.json)

    implementation(libs.androidx.datastore.preferences)

    implementation(libs.konfetti.compose)

    coreLibraryDesugaring(libs.desugar.jdk.libs)

    testImplementation(libs.junit)
    testImplementation(libs.kotlinx.coroutines.test)
    // Robolectric + an in-memory Room DB, so repository classes that touch QwDatabase directly
    // (ProgressRepositoryImpl, AchievementRepositoryImpl) can be exercised on the JVM test runner
    // instead of needing a connected device/emulator - this repo has no Android SDK configured by
    // default, so this is the only way these classes get real test coverage in CI.
    testImplementation(libs.robolectric)
    testImplementation(libs.androidx.test.core)
    testImplementation(libs.androidx.room.testing)
    androidTestImplementation(libs.androidx.espresso.core)
    androidTestImplementation(libs.androidx.junit)
    androidTestImplementation(libs.androidx.room.testing)
}

ksp {
    // Baseline schema export for future Room migration verification - see QwDatabase.kt's
    // exportSchema flag.
    arg("room.schemaLocation", "$projectDir/schemas")
}

tasks.matching { it.name == "extractReleaseNativeDebugMetadata" }.configureEach {
    val mergedLibs = layout.buildDirectory.dir("intermediates/merged_native_libs/release/mergeReleaseNativeLibs/out/lib")
    val outDir = layout.buildDirectory.dir("intermediates/native_debug_metadata/release/extractReleaseNativeDebugMetadata/out")
    doLast {
        val src = mergedLibs.get().asFile
        val dst = outDir.get().asFile
        if (src.exists()) {
            val localProps = rootProject.file("local.properties")
            val sdkPath = if (localProps.exists()) {
                val props = Properties()
                localProps.inputStream().use { props.load(it) }
                props.getProperty("sdk.dir")
            } else {
                System.getenv("ANDROID_HOME")
            }
            val ndkDir = sdkPath?.let { File(it, "ndk/28.2.13676358") }
            val objcopyExecutable = if (ndkDir != null && ndkDir.exists()) {
                ndkDir.walkTopDown().firstOrNull { it.name == "llvm-objcopy" && it.canExecute() }
            } else null

            src.walkTopDown().filter { it.isFile && it.extension == "so" }.forEach { soFile ->
                val relPath = soFile.relativeTo(src)
                val destDbg = File(dst, "${relPath.path}.dbg")
                destDbg.parentFile.mkdirs()
                if (objcopyExecutable != null) {
                    val process = ProcessBuilder(objcopyExecutable.absolutePath, "--only-keep-debug", soFile.absolutePath, destDbg.absolutePath).start()
                    process.waitFor()
                } else {
                    soFile.copyTo(destDbg, overwrite = true)
                }
            }
        }
    }
}

tasks.matching { it.name == "signReleaseBundle" }.configureEach {
    finalizedBy("mergeReleaseNativeDebugMetadata")
}

val copyReleaseArtifactsToRoot = tasks.register("copyReleaseArtifactsToRoot") {
    mustRunAfter("signReleaseBundle", "mergeReleaseNativeDebugMetadata")
    doLast {
        val ver = android.defaultConfig.versionName ?: "1.0.0"
        val bundleSrc = layout.buildDirectory.file("outputs/bundle/release/app-release.aab").get().asFile
        val bundleDest = rootProject.file("QuranicWords-v${ver}.aab")
        if (bundleSrc.exists()) {
            bundleSrc.copyTo(bundleDest, overwrite = true)
            logger.lifecycle("Copied signed release bundle to ${bundleDest.name} (${bundleDest.length()} bytes)")
        }
        val symbolsSrc = layout.buildDirectory.file("outputs/native-debug-symbols/release/native-debug-symbols.zip").get().asFile
        val symbolsDest = rootProject.file("QuranicWords-v${ver}-native-debug-symbols.zip")
        if (symbolsSrc.exists()) {
            symbolsSrc.copyTo(symbolsDest, overwrite = true)
            logger.lifecycle("Copied native debug symbols to ${symbolsDest.name} (${symbolsDest.length()} bytes)")
        }
        val apkSrc = layout.buildDirectory.file("outputs/apk/release/app-release.apk").get().asFile
        val apkDest = rootProject.file("QuranicWords-v${ver}.apk")
        if (apkSrc.exists()) {
            apkSrc.copyTo(apkDest, overwrite = true)
            logger.lifecycle("Copied release APK to ${apkDest.name} (${apkDest.length()} bytes)")
        }
    }
}

tasks.matching { it.name == "bundleRelease" }.configureEach {
    finalizedBy(copyReleaseArtifactsToRoot)
}

tasks.matching { it.name == "assembleRelease" }.configureEach {
    finalizedBy(copyReleaseArtifactsToRoot)
}



