#!/usr/bin/env python3
"""Builds the web app's data from the app's bundled curriculum (tools/pipeline output), so the
web dictionary and the Android app always teach exactly the same words and meanings.

    data/meanings/LANG.json  each word's meaning in one language, in index.json order
    data/index.json          every word, light fields only (loaded at start, ~1 MB)
    data/verses/LANG/ch_NN.json   per language and chapter: each word's proven senses (exact
                                  spans) and the verses they use, stored once (lazy-loaded)
    data/roots.json          root -> word ids
"""
import json
import re
import shutil
import unicodedata
from collections import defaultdict
from pathlib import Path

from slugs import word_slug

ROOT = Path(__file__).resolve().parents[2]
CONTENT = ROOT / "app" / "src" / "main" / "assets" / "content"
DATA = ROOT / "data"
SURAH_NAMES_KT = ROOT / "app/src/main/java/com/quranicwords/app/core/util/SurahNames.kt"
# Column order of SurahNames.Entry in the app; the web uses the same names so citations read
# identically in the app and on the site.
SURAH_COLUMNS = ["en", "ar", "bn", "ur", "hi", "in", "tr", "fr", "fa"]


def write_surah_names():
    """js/surahs.js: the app's localized names of all 114 surahs (single source of truth)."""
    rows = re.findall(r'Entry\(((?:"[^"]*",\s*){8}"[^"]*")\)', SURAH_NAMES_KT.read_text(encoding="utf-8"))
    rows = [re.findall(r'"([^"]*)"', r) for r in rows]
    if len(rows) != 114 or any(len(r) != 9 or not all(r) for r in rows):
        raise SystemExit(f"SurahNames.kt: expected 114 complete entries, got {len(rows)}")
    names = {lang: [r[i] for r in rows] for i, lang in enumerate(SURAH_COLUMNS) if lang != "ar"}
    body = json.dumps(names, ensure_ascii=False, indent=1)
    (ROOT / "js" / "surahs.js").write_text(
        "// Generated by tools/export/build_web_data.py from the app's SurahNames.kt - do not edit.\n"
        "// Localized names of the 114 surahs, index 0 = Al-Fatihah.\n"
        f"export const SURAH_NAMES = {body};\n", encoding="utf-8")
LANGS = ["en", "bn", "ur", "hi", "in", "tr", "fa", "fr"]


def skeleton(text):
    t = unicodedata.normalize("NFC", text or "")
    t = t.translate(str.maketrans({"أ": "ا", "إ": "ا", "آ": "ا", "ٱ": "ا", "ى": "ي", "ة": "ه", "ؤ": "و", "ئ": "ي"}))
    return "".join(c for c in t if "ء" <= c <= "ي")


def dump(path, obj):
    path.parent.mkdir(parents=True, exist_ok=True)
    path.write_text(json.dumps(obj, ensure_ascii=False, separators=(",", ":")), encoding="utf-8")


def main():
    chapters = json.loads((CONTENT / "chapters.json").read_text(encoding="utf-8"))["chapters"]
    sections = json.loads((CONTENT / "sections.json").read_text(encoding="utf-8"))["sections"]
    lessons = json.loads((CONTENT / "lessons_vocabulary.json").read_text(encoding="utf-8"))["lessons"]
    exercises = json.loads((CONTENT / "exercises_vocabulary.json").read_text(encoding="utf-8"))
    verses = json.loads((CONTENT / "verses.json").read_text(encoding="utf-8"))
    freq = {w["id"]: w for w in json.loads((CONTENT / "word_frequency.json").read_text(encoding="utf-8"))["words"]}

    ch_num = {c["id"]: c["sortOrder"] for c in chapters}
    sec_num = {s["id"]: s["sortOrder"] for s in sections}
    lesson_by_id = {l["id"]: l for l in lessons}
    regular_index = {}
    counters = defaultdict(int)
    for l in lessons:
        if l["kind"] == "REGULAR":
            counters[l["sectionId"]] += 1
            regular_index[l["id"]] = counters[l["sectionId"]]

    def pos_ref(label):
        if not label:
            return None
        key = json.dumps(label, sort_keys=True, ensure_ascii=False)
        if key not in pos_index:
            pos_index[key] = len(pos_table)
            pos_table.append(label)
        return pos_index[key]

    words, roots = [], defaultdict(list)
    meanings = {}            # id -> {lang: meaning}; written per language (only one is loaded)
    pos_table, pos_index = [], {}   # grammar labels stored once, words refer to them by index
    # per language, per chapter: senses of each word + the verses they use (stored once)
    per = defaultdict(lambda: {"words": {}, "verses": {}})
    for e in exercises:
        if e["exerciseType"] != "WORD_INTRO":
            continue
        c = e["content"]
        lesson = lesson_by_id[e["lessonId"]]
        f = freq[c["wordId"]]
        ch = ch_num[lesson["chapterId"]]
        first = c["senses"]["en"][0]
        words.append({
            "id": c["wordId"], "ar": c["arabicWord"], "tl": c.get("transliteration", ""),
            "rt": c.get("root"), "cat": c["lemmaCategory"], "p": pos_ref(c.get("partOfSpeechLabel") or c.get("verbFormLabel")),
            "ch": ch, "sec": sec_num[lesson["sectionId"]], "les": regular_index[e["lessonId"]],
            "occ": c["quranOccurrenceCount"], "rank": f["frequencyRank"],
            # English stays in the index: it is the fallback, and older cached copies of the web
            # app read w.m.en directly (they would crash without it). Other languages are in
            # data/meanings/LANG.json.
            "m": {"en": c["meaning"]["en"]},
            "ref": verses[first["verse"]]["ref"],
            "u": word_slug(c["wordId"], c.get("transliteration")),     # quran-words/<u>.html
            "sk": skeleton(c["arabicWord"]),
            "poly": {lang: len(items) for lang, items in c["senses"].items() if len(items) > 1},
            "vf": {k: c[k] for k in ("verbForm", "pastArabic", "presentArabic", "masdarArabic") if c.get(k)} or None,
        })
        meanings[c["wordId"]] = c["meaning"]
        for lang in LANGS:
            bucket = per[(lang, ch)]
            items = []
            for sn in c["senses"][lang]:
                v = verses[sn["verse"]]
                bucket["verses"][sn["verse"]] = {"ref": v["ref"], "ar": v["ar"], "wbw": v["wbw"][lang], "tr": v["tr"][lang]}
                items.append({"m": sn["meaning"], "v": sn["verse"], "s": sn["wordStart"], "e": sn["wordEnd"],
                              "ws": sn["wbwStart"], "we": sn["wbwEnd"],
                              "ts": sn["translationStart"], "te": sn["translationEnd"]})
            bucket["words"][c["wordId"]] = items
        if c.get("root"):
            roots[c["root"]].append(c["wordId"])
    words.sort(key=lambda w: w["rank"])
    for w in words:
        if w["p"] is None:
            del w["p"]

    total = sum(c["quranOccurrenceCount"] for c in chapters)
    meta = {
        "version": "3", "languages": LANGS, "wordCount": len(words), "rootCount": len(roots),
        "occurrences": total,
        "pos": pos_table,
        "coveragePercent": round(sum(c["quranOccurrencePercent"] for c in chapters), 1),
        "chapters": [{"n": c["sortOrder"], "id": c["id"], "title": c["title"], "words": c["wordCount"],
                      "pct": c["quranOccurrencePercent"]} for c in chapters],
    }
    if (DATA / "verses").exists():
        shutil.rmtree(DATA / "verses")
    for stale in ("words.json", "words_summary.json", "metadata.json"):
        (DATA / stale).unlink(missing_ok=True)
    write_surah_names()
    dump(DATA / "index.json", {"meta": meta, "words": words})
    # One meanings file per language, aligned with index.json's word order.
    for stale in (DATA / "meanings").glob("*.json") if (DATA / "meanings").exists() else []:
        stale.unlink()
    for lang in LANGS:
        if lang != "en":
            dump(DATA / "meanings" / f"{lang}.json", [meanings[w["id"]][lang] for w in words])
    for (lang, ch), bucket in per.items():
        dump(DATA / "verses" / lang / f"ch_{ch:02d}.json", bucket)
    dump(DATA / "roots.json", {r: ids for r, ids in sorted(roots.items(), key=lambda kv: -len(kv[1]))})
    print(f"{len(words)} words, {len(roots)} roots, {len(per)} verse files -> {DATA}")


if __name__ == "__main__":
    main()
