package com.quranicwords.app.core.ui.components

import androidx.annotation.RawRes
import androidx.compose.runtime.Composable
import androidx.compose.runtime.getValue
import androidx.compose.ui.Modifier
import com.airbnb.lottie.compose.LottieAnimation
import com.airbnb.lottie.compose.LottieCompositionSpec
import com.airbnb.lottie.compose.animateLottieCompositionAsState
import com.airbnb.lottie.compose.rememberLottieComposition
import com.quranicwords.app.core.ui.motion.rememberReducedMotion

/**
 * Plays a bundled Lottie JSON once on first composition (e.g. the splash "light unfold" reveal).
 * [rawResId] is null until a real asset is bundled under `res/raw/` (see the redesign plan's
 * Asset Plan - an external content dependency, not something generated by code); with no asset,
 * [fallback] renders instead so the screen degrades gracefully rather than showing nothing.
 * Under reduced motion, jumps straight to the final frame instead of animating.
 */
@Composable
fun LottieOneShot(
    @RawRes rawResId: Int?,
    modifier: Modifier = Modifier,
    fallback: @Composable () -> Unit = {}
) {
    if (rawResId == null) {
        fallback()
        return
    }

    val reducedMotion = rememberReducedMotion()
    val composition by rememberLottieComposition(LottieCompositionSpec.RawRes(rawResId))
    val progress by animateLottieCompositionAsState(
        composition = composition,
        iterations = 1,
        speed = 1f,
        isPlaying = !reducedMotion
    )
    LottieAnimation(
        composition = composition,
        progress = { if (reducedMotion) 1f else progress },
        modifier = modifier
    )
}
