package com.quranicwords.app.core.ui.components

import androidx.annotation.RawRes
import androidx.compose.foundation.layout.size
import androidx.compose.material.icons.Icons
import androidx.compose.material.icons.filled.Whatshot
import androidx.compose.material3.Icon
import androidx.compose.runtime.Composable
import androidx.compose.ui.Modifier
import androidx.compose.ui.unit.dp
import androidx.compose.ui.viewinterop.AndroidView
import app.rive.runtime.kotlin.RiveAnimationView
import com.quranicwords.app.core.ui.theme.StreakAccent

/**
 * Streak flame with a Rive state-machine input ("streakDays") that scales the flame's
 * intensity/speed live, instead of swapping between static assets per streak tier.
 *
 * [riveResId] is null until a real `.riv` file is bundled under `res/raw/` (see the redesign
 * plan's Asset Plan - this is an external content dependency, not something generated by code).
 * With no asset supplied, this renders the prior static flame icon so the app looks and behaves
 * identically to before until the asset lands - swap in a resource id then. The exact
 * `RiveAnimationView`/state-machine-input method names below should be re-verified against the
 * installed `rive-android` version once a real build (Android SDK + asset) is available to test
 * against; they weren't compile-checked in this environment.
 */
@Composable
fun RiveStreakFlame(
    streakDays: Int,
    modifier: Modifier = Modifier,
    @RawRes riveResId: Int? = null,
    stateMachineName: String = "StreakFlame",
    streakInputName: String = "streakDays"
) {
    if (riveResId == null) {
        Icon(
            imageVector = Icons.Filled.Whatshot,
            contentDescription = null,
            tint = StreakAccent,
            modifier = modifier.size(24.dp)
        )
        return
    }

    AndroidView(
        modifier = modifier.size(48.dp),
        factory = { context ->
            RiveAnimationView(context).apply {
                setRiveResource(
                    resId = riveResId,
                    stateMachineName = stateMachineName,
                    autoplay = true
                )
            }
        },
        update = { view ->
            runCatching { view.setNumberState(stateMachineName, streakInputName, streakDays.toFloat()) }
        }
    )
}
